services: 
  mongo:
    image: initialized-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    ports:
     - 3456:27017
    volumes: 
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    command: ['redis-server', '--appendonly', 'yes']
    volumes: # Declare the volume
      - ./redis_data:/data  
volumes:
  mongo_data: